require 'redis-queue'

require_relative 'defaults'
require_relative 'environment'

Monday::Queue.queue.push 'http://www.aetna.com/dse/search?site_id=docfind&langpref=en&tabKey=tab1#markPage=clickedPagination&whyPressed=geo&searchQuery=All%20Behavioral%20Health%20Professionals&searchTypeMainTypeAhead=&searchTypeThrCol=byProvType&mainTypeAheadSelectionVal=&thrdColSelectedVal=All%20Behavioral%20Health%20Professionals&aetnaId=&Quicklastname=&Quickfirstname=&QuickZipcode=1019%5C9&QuickCoordinates=40.7427%2C-73.99340000000001&quickCategoryCode=&QuickGeoType=city&geoSearch=New%20York%20City%2C%20New%20York&geoMainTypeAheadLastQuickSelectedVal=New%20York%20City%2C%20New%20Yo%5Crk&geoBoxSearch=true&stateCode=NY&quickSearchTerm=&classificationLimit=&pcpSearchIndicator=&specSearchIndicator=&suppressFASTDocCall=true&linkwithoutplan=&publicPlan=AWMTS&displayPlan=%28NY%29%20Ae%5Ctna%20Whole%20Health%u2120%20-%20Mount%20Sinai%20Health%20Partners%20Plus&zip=&filterValues=&pagination=&radius=0&lastPageTravVal=&sendZipLimitInd=&site_id=docfind&sortOrder=distance&ioeqSelectionInd=&ioe_qType=&switchForStatePlanSelectionPopUp=&actualDisplayTerm=All%20Behavioral%20Health%20Professionals&withinMilesVal='
Monday::Queue.queue.push 'http://www.aetna.com/dse/search?site_id=docfind&langpref=en&tabKey=tab1#markPage=clickedPagination&whyPressed=geo&searchQuery=All%20Behavioral%20Health%20Professionals&searchTypeMainTypeAhead=&searchTypeThrCol=byProvType&mainTypeAheadSelectionVal=&thrdColSelectedVal=All%20Behavioral%20Health%20Professionals&aetnaId=&Quicklastname=&Quickfirstname=&QuickZipcode=1019%5C9&QuickCoordinates=40.7427%2C-73.99340000000001&quickCategoryCode=&QuickGeoType=city&geoSearch=New%20York%20City%2C%20New%20York&geoMainTypeAheadLastQuickSelectedVal=New%20York%20City%2C%20New%20Yo%5Crk&geoBoxSearch=true&stateCode=NY&quickSearchTerm=&classificationLimit=&pcpSearchIndicator=&specSearchIndicator=&suppressFASTDocCall=true&linkwithoutplan=&publicPlan=AWMTS&displayPlan=%28NY%29%20Ae%5Ctna%20Whole%20Health%u2120%20-%20Mount%20Sinai%20Health%20Partners%20Plus&zip=&filterValues=&pagination=25&radius=0&lastPageTravVal=&sendZipLimitInd=&site_id=docfind&sortOrder=distance&ioeqSelectionInd=&ioe_qType=&switchForStatePlanSelectionPopUp=&actualDisplayTerm=All%20Behavioral%20Health%20Professionals&withinMilesVal='
Monday::Queue.queue.push 'http://www.aetna.com/dse/search?site_id=docfind&langpref=en&tabKey=tab1#markPage=clickedPagination&whyPressed=geo&searchQuery=All%20Behavioral%20Health%20Professionals&searchTypeMainTypeAhead=&searchTypeThrCol=byProvType&mainTypeAheadSelectionVal=&thrdColSelectedVal=All%20Behavioral%20Health%20Professionals&aetnaId=&Quicklastname=&Quickfirstname=&QuickZipcode=1019%5C9&QuickCoordinates=40.7427%2C-73.99340000000001&quickCategoryCode=&QuickGeoType=city&geoSearch=New%20York%20City%2C%20New%20York&geoMainTypeAheadLastQuickSelectedVal=New%20York%20City%2C%20New%20Yo%5Crk&geoBoxSearch=true&stateCode=NY&quickSearchTerm=&classificationLimit=&pcpSearchIndicator=&specSearchIndicator=&suppressFASTDocCall=true&linkwithoutplan=&publicPlan=AWMTS&displayPlan=%28NY%29%20Ae%5Ctna%20Whole%20Health%u2120%20-%20Mount%20Sinai%20Health%20Partners%20Plus&zip=&filterValues=&pagination=50&radius=0&lastPageTravVal=&sendZipLimitInd=&site_id=docfind&sortOrder=distance&ioeqSelectionInd=&ioe_qType=&switchForStatePlanSelectionPopUp=&actualDisplayTerm=All%20Behavioral%20Health%20Professionals&withinMilesVal='
Monday::Queue.queue.push 'http://www.aetna.com/dse/search?site_id=docfind&langpref=en&tabKey=tab1#markPage=clickedPagination&whyPressed=geo&searchQuery=All%20Behavioral%20Health%20Professionals&searchTypeMainTypeAhead=&searchTypeThrCol=byProvType&mainTypeAheadSelectionVal=&thrdColSelectedVal=All%20Behavioral%20Health%20Professionals&aetnaId=&Quicklastname=&Quickfirstname=&QuickZipcode=1019%5C9&QuickCoordinates=40.7427%2C-73.99340000000001&quickCategoryCode=&QuickGeoType=city&geoSearch=New%20York%20City%2C%20New%20York&geoMainTypeAheadLastQuickSelectedVal=New%20York%20City%2C%20New%20Yo%5Crk&geoBoxSearch=true&stateCode=NY&quickSearchTerm=&classificationLimit=&pcpSearchIndicator=&specSearchIndicator=&suppressFASTDocCall=true&linkwithoutplan=&publicPlan=AWMTS&displayPlan=%28NY%29%20Ae%5Ctna%20Whole%20Health%u2120%20-%20Mount%20Sinai%20Health%20Partners%20Plus&zip=&filterValues=&pagination=75&radius=0&lastPageTravVal=&sendZipLimitInd=&site_id=docfind&sortOrder=distance&ioeqSelectionInd=&ioe_qType=&switchForStatePlanSelectionPopUp=&actualDisplayTerm=All%20Behavioral%20Health%20Professionals&withinMilesVal='
